  const nwsToOriginalIconMappingDay = {
    'Clear': '1',
    'Mostly Clear': '2',
    'Mostly Sunny': '2',
    'Partly Cloudy': '3',
    'Partly Sunny': '3',
    'Mostly Cloudy': '6',
    'Cloudy': '7',
    'Overcast': '8',
    'Fog': '11',
    'Dense Fog': '11',
    'Haze': '5',
    'Smoke': '5',
    'Drizzle': '12',
    'Rain': '18',
    'Heavy Rain': '18',
    'Freezing Rain': '26',
    'Sleet': '25',
    'Snow': '22',
    'Heavy Snow': '22',
    'Blowing Snow': '22',
    'Snow Showers': '22',
    'Snow Flurries': '22',
    'Thunderstorm': '15',
    'Severe Thunderstorm': '15',
    'Tornado': '15',
    'Hurricane': '15',
    'Tropical Storm': '15',
    'Blizzard': '19',
    'Ice Storm': '24',
    'Windy': '32',
    'Breezy': '32',
    'Gusty Winds': '32',
    'Calm': '2',
    'Hot': '30',
    'Cold': '31',
    'Frost': '24',
    'Freeze': '24',
    'Dust Storm': '5',
    'Sandstorm': '5',
    'Hail': '25',
    'Freezing Fog': '11',
    'Patchy Fog': '11',
    'Light Rain': '13',
    'Light Snow': '20',
    'Scattered Showers': '13',
    'Isolated Thunderstorms': '16'
  };

  const nwsToOriginalIconMappingNight = {
    'Clear': '33',
    'Mostly Clear': '34',
    'Partly Cloudy': '35',
    'Mostly Cloudy': '38',
    'Cloudy': '7',
    'Overcast': '8',
    'Fog': '11',
    'Dense Fog': '11',
    'Haze': '37',
    'Smoke': '37',
    'Drizzle': '39',
    'Rain': '18',
    'Heavy Rain': '18',
    'Freezing Rain': '26',
    'Sleet': '25',
    'Snow': '22',
    'Heavy Snow': '22',
    'Blowing Snow': '22',
    'Snow Showers': '22',
    'Snow Flurries': '22',
    'Thunderstorm': '15',
    'Severe Thunderstorm': '15',
    'Tornado': '32',
    'Hurricane': '32',
    'Tropical Storm': '15',
    'Blizzard': '22',
    'Ice Storm': '24',
    'Windy': '32',
    'Breezy': '32',
    'Gusty Winds': '32',
    'Calm': '34',
    'Hot': '30',
    'Cold': '31',
    'Frost': '24',
    'Freeze': '24',
    'Dust Storm': '37',
    'Sandstorm': '37',
    'Hail': '25',
    'Freezing Fog': '11',
    'Patchy Fog': '11',
    'Light Rain': '39',
    'Light Snow': '44',
    'Scattered Showers': '40',
    'Isolated Thunderstorms': '42'
  };

  // Function to return the original icon URL based on the short forecast and time of day.
  const getOriginalIconUrl = (shortForecast, isDaytime = true) => {
    const mapping = isDaytime ? nwsToOriginalIconMappingDay : nwsToOriginalIconMappingNight;
    for (const key in mapping) {
      if (shortForecast.includes(key)) {
        return `https://developer.accuweather.com/sites/default/files/${mapping[key]}.png`;
      }
    }
    // Fallback if no mapping is found:
    return `https://developer.accuweather.com/sites/default/files/${isDaytime ? '1' : '33'}.png`;
  };
